---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb-svc
  namespace: default
spec:
  ports:
  - nodePort: 30002
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb # Label to match service to deployment
  type: NodePort