---
# YAML is case sensitive
# use spaces not a tab
apiVersion: apps/v1 # specify api to use for deployment
kind: Deployment # kind of service/object you want to create
metadata:
  name: spartafullapp-deployment # name the deployment
spec:
  selector:
    matchLabels:
      app: mongodb  # look for this label/tab to match the k8 service
# create a ReplicaSet with instances/pods
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.6 # the image you creat>
        ports:
        - containerPort: 27017
      
