---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb-syc
  namespace: default
spec:
  ports:
  - protocol: TCP 
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: NodePort