---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-syc
  namespace: default
spec:
  ports:
  - nodePort: 30001 #range is 30000-32768
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort